spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?createDatabaseIfNotExist=true
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org.hibernate.SQL: debug

server:
  port: 8080
  address: localhost
